# Importamos librerías necesarias

In [34]:
import pandas as pd
import numpy as np
import re
import pycountry
import string
from datetime import datetime
import country_converter as coco

# Cargamos la información del cvs y hacemos un primer análisis

In [2]:
df=pd.read_csv('./GSAF5.csv',  engine='python', header=0)
df.head(100)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,...,Blue shark,"Informacion.es, 7/29/2016",2016.07.29-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.29,2016.07.29,5973,NaN,NaN
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,...,NaN,"Klassick, 7/28/2016",2016.07.28.R-Franz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28.R,2016.07.28.R,5972,NaN,NaN
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,...,White shark,"ABC Australia, 7/28/2016",2016.07.28-Watkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28,2016.07.28,5971,NaN,NaN
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,...,"Nurse shark, 4'","Tampa Bay Times, 7/27/2016",2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.27,2016.07.27,5970,NaN,NaN
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,...,NaN,"Gold Coast Bulletin, 7/28/2016",2016.07.26-Ballina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.26,2016.07.26,5969,NaN,NaN
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,...,NaN,"Japan Times, 7/25/2016",2016.07.24-Japan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.24,2016.07.24,5968,NaN,NaN
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,...,NaN,"C. Black, GSAF",2016.07.23.b-Critchlow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.b,2016.07.23.b,5967,NaN,NaN
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,...,"Bull shark, 6'","KWTX, 7/23/2016",2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.a,2016.07.23.a,5966,NaN,NaN
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,...,"reef shark, 1m","Nine News, 7/20/2016",2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.20,2016.07.20,5965,NaN,NaN
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,...,"Tiger shark, 10'","Al.com, 7/19/2016",2016.07.17-Gulf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.17,2016.07.17,5964,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2016.04.18,18-Apr-16,2016,Provoked,FRENCH POLYNESIA,Tuamotos,Makemo Atoll,Spearfishing,Teva Tokoragi,M,...,"Grey reef shark, 2 m","Tahiti Infos, 4/19/2016",2016.04.18-Tokoragi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.18,2016.04.18,5923,NaN,NaN
71,2016.04.13,13-Apr-16,2016,Unprovoked,USA,Florida,"Off Singer Island, Palm Beach County",Spearfishing,Kyle Senkowicz,M,...,"Bull shark, 7'","Palm Beach Post, 4/13/2016",2016.04.13-Senkowicz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.13,2016.04.13,5922,NaN,NaN
72,2016.04.09,09-Apr-16,2016,Unprovoked,NEW CALEDONIA,Grand Terre,Poe Beach,Walking,Nicole Malignon,F,...,"Tiger shark, 2.5 m",Les Nouvelles Caledonnie. 4/11/2016,2016.04.09-Malignon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.09,2016.04.09,5921,NaN,NaN
73,2016.04.08,08-Apr-16,2016,Invalid,CAPE VERDE,Boa Vista Island,NaN,NaN,a British citizen,M,...,Shark involvement not confirmed,L.O.Guttke,2016.04.08-CapeVerde.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.08,2016.04.08,5920,NaN,NaN
74,2016.04.07.b,07-Apr-16,2016,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Fishing,Jonathan Lester,M,...,5' to 6' shark,NaN,2016.04.07.b-Lester.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.07.b,2016.04.07.b,5919,NaN,NaN
75,2016.04.07.a,07-Apr-16,2016,Invalid,USA,Florida,"Corners Beach, Jupiter, Palm Beach County",SUP,Maximo Trinidad,M,...,NaN,YouTube,2016.04.07.a-Trinidad.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.07.a,2016.04.07.a,5918,NaN,NaN
76,2016.03.31,31-Mar-16,2016,Unprovoked,USA,Hawaii,"Olowalu, Maui",Snorkeling,J. Orr,F,...,NaN,"Maui Now, 3/31/2016",2016.03.31-Orr.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.31,2016.03.31,5917,NaN,NaN
77,2016.03.30,30-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,Bombo Beach,Surfing,Brett Connellan,M,...,NaN,"Daily Telegraph, 3/30/2016",2016.03.30-Connellan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.30,2016.03.30,5916,NaN,NaN
78,2016.03.28.b,28-Mar-16,2016,Unprovoked,USA,Florida,"Fort Myers Beach, Lee County",NaN,Nick Kawa,M,...,Shark involvement not confirmed,"Fox 35, 3/30/2015",2016.03.28.b-Kawa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.28.b,2016.03.28.b,5915,NaN,NaN
79,2016.03.28.a,28-Mar-16,2016,Unprovoked,AUSTRALIA,New South Wales,North Cronulla Beach,Surfing,Roie Smyth,M,...,NaN,"B. Myatt, GSAF",2013.03.28.a-Smyth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.28.a,2016.03.28.a,5914,NaN,NaN
80,2016.03.26,26-Mar-16,2016,Provoked,BAHAMAS,NaN,NaN,NaN,Henry Kreckman,M,...,"Nurse shark, 2.5-ft","Wisconsin State Journal, 4/2/2016",2016.03.26-Kreckman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.26,2016.03.26,5913,NaN,NaN
81,2016.03.13,13-Mar-16,2016,Invalid,USA,California,"Bolsa Chica State Park, Orange County",Surfing,unknown,NaN,...,Shark involvement not confirmed,"Orange County Register, 3/13/2016",2016.03.13-BolsaChicaSurfer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.13,2016.03.13,5912,NaN,NaN
82,2016.03.11,11-Mar-16,2016,Unprovoked,USA,Florida,"Vero Beach, St. Lucie County",Body surfing,Daniel Kenny,M,...,NaN,"WCBV-5, 3/31/206",2016.03.11-Kenny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.11,2016.03.11,5911,NaN,NaN
83,2016.03.10,10-Mar-16,2016,Unprovoked,Fiji,Vanua Levu,NaN,Diving for beche-de-mer,Maika Tabua,M,...,NaN,"Fiji Sun, 3/12/2016",2016.03.10-Tabua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.10,2016.03.10,5910,NaN,NaN
84,2016.03.04,04-Mar-16,2016,Unprovoked,USA,Florida,"Ocean Reef Park, Singer Island, Palm Beach County",NaN,male,M,...,NaN,WPTV. 3/4/2016,2016.03.04-OCPark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.04,2016.03.04,5909,NaN,NaN
85,2016.03.03.R,Reported 03-Mar-2016,2016,Unprovoked,AUSTRALIA,South Australia,Wrights Bay,Fishing,Lee Taplin,M,...,Bronze whaler,"9 News, 3/1/2016",2016.03.03.R-Taplin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.03.R,2016.03.03.R,5908,NaN,NaN
86,2016.03.02,02-Mar-16,2016,Unprovoked,BRAZIL,Santa Catarina State,Escalerio Beach Balneário Camboriú,Swimming,Rafael Hermes Thomas,M,...,Sandtiger shark,"Misones Online, 3/4/2016",2016.03.02-Thomas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.03.02,2016.03.02,5907,NaN,NaN
87,2016.02.22,22-Feb-16,2016,Unprovoked,NEW CALEDONIA,South Province,"Ricaudy Reef, Noumea",Kite surfing,Adrian *,M,...,NaN,"Les Nouvelles Calédoniennes, 2/23/2016",2016.02.22-Noumea.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.22,2016.02.22,5906,NaN,NaN
88,2016.02.19,19-Feb-2016,2016,Unprovoked,NEW CALEDONIA,South Province,Yate,Spearfishing,male,M,...,NaN,"Les Nouvelles Calédoniennes, 2/19/2016",2016.02.19-NewCaledonia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.19,2016.02.19,5905,NaN,NaN
89,2016.02.12,12-Feb-16,2016,Unprovoked,DOMINICAN REPUBLIC,Altagracia Province,"Bavaro Beach, Punta Cana",Wading,Patricia Howe,F,...,NaN,S. Harris,2016.02.12-Howe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.12,2016.02.12,5904,NaN,NaN
90,2016.02.10.R,Reported 10-Feb-2016,2016,Invalid,CAYMAN ISLANDS,Grand Cayman,Stingray City Bar,Feeding stingrays?,Richard Branson,M,...,No shark involvement,R. Branson,2016.02.10.R-Branson-stingray.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.10.R,2016.02.10.R,5903,NaN,NaN
91,2016.02.10,10-Feb-16,2016,Invalid,AUSTRALIA,Tasmania,Nettley Bay,Surfing,male,M,...,No shark involvement,"C. Black, GSAF",2016.02.11-NettleyBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.10,2016.02.10,5902,NaN,NaN
92,2016.02.05,05-Feb-16,2016,Unprovoked,AUSTRALIA,Queensland,Stradbroke Island,Walking,female,F,...,NaN,"Courier Mail, 2/5/2016",2016.02.05-Stradbroke.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.05,2016.02.05,5901,NaN,NaN
93,2016.02.04,04-Feb-16,2016,Unprovoked,AUSTRALIA,New South Wales,Hams Beach,Windsurfing,Andrew Morris,M,...,NaN,"B. Myatt, GSAF",2016.02.04-Morris.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.02.04,2016.02.04,5900,NaN,NaN
94,2016.01.29,29-Jan-16,2016,Boat,SOUTH AFRICA,KwaZulu-Natal,NaN,Kayak fishing,Dev De Lange,M,...,NaN,"Nine News, 2/1/2016",2016.01.29-DeLange.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.01.29,2016.01.29,5899,NaN,NaN
95,2016.01.28,28-Jan-16,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai",Surfing,male,M,...,"Reef shark, 5'",KHON2. 1/28/2016,2016.01.28-Kauai.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.01.28,2016.01.28,5898,NaN,NaN
96,2016.01.25,25-Jan-16,2016,Unprovoked,USA,Hawaii,"Hanalei Bay, Kauai,",Surfing,Kaya Waldman,F,...,NaN,"The Garden Island, 2/2/2016",2016.01.25-Waldman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.01.25,2016.01.25,5897,NaN,NaN
97,2016.01.24.b,24-Jan-16,2016,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,M,...,Bull sharks x 2,K. Love,2016.01.24.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.24.b,2016.01.24.b,5896,NaN,NaN
98,2016.01.24.a,24-Jan-16,2016,Boat,UNITED ARAB EMIRATES,Fujairah Emirate,35 miles off Fujairah,Fishing,Occupants: Hamza Humaid Al Sahra’a & 5 crew,M,...,Mako shark,"Gulf News, 1/25/2016",2016.01.24.a-UAEboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.01.24.a,2016.01.24.a,5895,NaN,NaN
99,2016.01.23,23-Jan-16,2016,Unprovoked,USA,Hawaii,"Wailea Beach, Maui",Paddle boarding,Matt Mason,M,...,"Tiger shark, 14'","Grand Forks Herald, 1/27/2915",2016.01.23-Mason.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.01.23,2016.01.23,5894,NaN,NaN

In [3]:
df.count()

Case Number               5992
Date                      5992
Year                      5992
Type                      5992
Country                   5949
Area                      5590
Location                  5496
Activity                  5465
Name                      5792
Sex                       5425
Age                       3311
Injury                    5965
Fatal (Y/N)               5973
Time                      2779
Species                   3058
Investigator or Source    5977
pdf                       5992
href formula              5991
href                      5989
Case Number.1             5992
Case Number.2             5992
original order            5992
Unnamed: 22                  1
Unnamed: 23                  2
dtype: int64

In [4]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

# Cleaning column names

In [5]:
# Renombramos columnas
df.columns=[str.strip(x.lower()) for x in df.columns]
df.columns=[re.sub(r"[. \ :+]","_",x) for x in df.columns]
df.columns=[re.sub("__","_",x) for x in df.columns]

df = df.rename(columns={'fatal_(y/n)':'fatal'})

In [6]:
df.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number_1', 'case_number_2', 'original_order', 'unnamed_22',
       'unnamed_23'],
      dtype='object')

In [7]:
column_order = ['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number_1', 'case_number_2', 'original_order', 'unnamed_22',
       'unnamed_23']
df=df[column_order]
df.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number_1', 'case_number_2', 'original_order', 'unnamed_22',
       'unnamed_23'],
      dtype='object')

In [8]:
# Guardamos una copia del dataset antes del wrangling
df_Original=df

# Clean all dates(date,case_number,case_number_1,case_number_2)

## Aplicamos una función para encontrar las fechas en estos campos y pasar la columna a fecha

In [9]:
def clean_date(date):
    date = re.search('\d{4,}[-./|]\d{2,}[-./|]\d{2,}', date)
    if date:
        str_date =date.group()
        str_date = str_date[0:4] +'/'+ str_date[5:7] +'/'+ str_date[8:10]
        try: 
            clean_date = datetime.strptime(str_date, '%Y/%m/%d').date()
        except:
            clean_date = None
            pass
    else: 
        clean_date = None
    return(clean_date)
    
df['case_number_c'] = df.case_number.apply(lambda x:clean_date(x))
df['case_number_1_c'] = df.case_number_1.apply(lambda x:clean_date(x))
df['case_number_2_c'] = df.case_number_2.apply(lambda x:clean_date(x))

## Verificamos que los valores sean correctos

In [10]:
df['case_number_c'].value_counts()

2001-04-12    5
2003-10-05    5
1995-07-28    5
2014-12-28    4
2012-06-14    4
2010-01-09    4
1952-07-27    4
1906-10-10    4
1970-01-23    4
1994-07-09    4
2008-12-27    4
2015-09-20    4
2012-06-26    3
2011-08-16    3
2014-03-18    3
1916-07-12    3
2008-06-26    3
2010-02-06    3
2007-09-30    3
2008-03-28    3
1962-01-11    3
2002-09-27    3
1977-03-13    3
2003-06-24    3
2011-06-06    3
2012-09-02    3
2001-04-11    3
2003-04-20    3
1972-01-01    3
1899-08-08    3
             ..
2007-02-03    1
1905-03-26    1
1955-10-16    1
2000-02-19    1
1956-09-23    1
1988-04-10    1
2012-05-12    1
1907-10-18    1
1948-02-12    1
1977-05-16    1
1994-04-02    1
2011-08-18    1
1993-06-29    1
2009-08-01    1
1985-09-28    1
1960-04-12    1
1932-06-20    1
1972-10-22    1
1992-09-11    1
1951-05-09    1
2006-03-28    1
2013-04-21    1
1914-05-31    1
1991-02-24    1
1951-08-16    1
1977-08-31    1
2015-01-24    1
2007-11-06    1
2008-01-27    1
1958-06-26    1
Name: case_number_c, Length: 4507, dtype: int64

## Como inferimos el campo desde otras columnas vemos que todos los campos son casi iguales, salvo 5 casos, por eso tomamos la desición de que tomar como fecha los registros que coindidan todos

In [11]:
df['match_all_date']=(df['case_number_c']==df['case_number_1_c'])&(df['case_number_1_c']==df['case_number_2_c'])
df['match_1']=(df['case_number_c']==df['case_number_1_c'])
df['match_2']=(df['case_number_1_c']==df['case_number_2_c'])
df['match_3']=(df['case_number_2_c']==df['case_number_c'])

print(df['match_all_date'].value_counts())
print(df['match_1'].value_counts())
print(df['match_2'].value_counts())
print(df['match_3'].value_counts())

True     5126
False     866
Name: match_all_date, dtype: int64
True     5126
False     866
Name: match_1, dtype: int64
True     5127
False     865
Name: match_2, dtype: int64
True     5131
False     861
Name: match_3, dtype: int64

In [12]:
df['date_c'] = None
df['date_c'] = df.loc[df['match_all_date']==True, 'case_number_c']

In [13]:
df.head()

,case_number,date,year,type,country,area,location,activity,name,sex,...,unnamed_22,unnamed_23,case_number_c,case_number_1_c,case_number_2_c,match_all_date,match_1,match_2,match_3,date_c
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,NaN,2016-09-17,2016-09-17,2016-09-17,True,True,True,True,2016-09-17
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,NaN,NaN,2016-09-15,2016-09-16,2016-09-15,False,False,False,True,NaN

# Clean Unnamed:  22 - Borramos columna por el número de nulls

In [14]:
df[df['unnamed_22'].notnull()]

,case_number,date,year,type,country,area,location,activity,name,sex,...,unnamed_22,unnamed_23,case_number_c,case_number_1_c,case_number_2_c,match_all_date,match_1,match_2,match_3,date_c
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,...,stopped here,NaN,2006-06-18,2006-06-18,2006-06-18,True,True,True,True,2006-06-18

In [15]:
df.drop(['unnamed_22'], axis=1)

,case_number,date,year,type,country,area,location,activity,name,sex,...,original_order,unnamed_23,case_number_c,case_number_1_c,case_number_2_c,match_all_date,match_1,match_2,match_3,date_c
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5993,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,5992,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5991,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,5990,NaN,2016-09-17,2016-09-17,2016-09-17,True,True,True,True,2016-09-17
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,5989,NaN,2016-09-15,2016-09-16,2016-09-15,False,False,False,True,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,5988,NaN,2016-09-15,2016-09-15,2016-09-15,True,True,True,True,2016-09-15
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,5987,NaN,2016-09-11,2016-09-11,2016-09-11,True,True,True,True,2016-09-11
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,5986,NaN,2016-09-07,2016-09-07,2016-09-07,True,True,True,True,2016-09-07
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,5985,NaN,2016-09-06,2016-09-06,2016-09-06,True,True,True,True,2016-09-06
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,5984,NaN,2016-09-05,2016-09-05,2016-09-05,True,True,True,True,2016-09-05
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,5983,NaN,2016-09-05,2016-09-05,2016-09-05,True,True,True,True,2016-09-05
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,5982,NaN,2016-09-04,2016-09-04,2016-09-04,True,True,True,True,2016-09-04
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,5981,NaN,2016-09-01,2016-09-01,2016-09-01,True,True,True,True,2016-09-01
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,5980,NaN,2016-08-29,2016-08-29,2016-08-29,True,True,True,True,2016-08-29
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5979,NaN,2016-08-29,2016-08-29,2016-08-29,True,True,True,True,2016-08-29
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,5978,NaN,2016-08-27,2016-08-27,2016-08-27,True,True,True,True,2016-08-27
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,5977,NaN,2016-08-25,2016-08-25,2016-08-25,True,True,True,True,2016-08-25
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,5976,NaN,2016-08-07,2016-08-07,2016-08-07,True,True,True,True,2016-08-07
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,5975,NaN,2016-08-06,2016-08-06,2016-08-06,True,True,True,True,2016-08-06
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,5974,NaN,2016-08-04,2016-08-04,2016-08-04,True,True,True,True,2016-08-04
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,...,5973,NaN,2016-07-29,2016-07-29,2016-07-29,True,True,True,True,2016-07-29
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,...,5972,NaN,2016-07-28,2016-07-28,2016-07-28,True,True,True,True,2016-07-28
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,...,5971,NaN,2016-07-28,2016-07-28,2016-07-28,True,True,True,True,2016-07-28
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,...,5970,NaN,2016-07-27,2016-07-27,2016-07-27,True,True,True,True,2016-07-27
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,...,5969,NaN,2016-07-26,2016-07-26,2016-07-26,True,True,True,True,2016-07-26
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,...,5968,NaN,2016-07-24,2016-07-24,2016-07-24,True,True,True,True,2016-07-24
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,...,5967,NaN,2016-07-23,2016-07-23,2016-07-23,True,True,True,True,2016-07-23
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,...,5966,NaN,2016-07-23,2016-07-23,2016-07-23,True,True,True,True,2016-07-23
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,...,5965,NaN,2016-07-20,2016-07-20,2016-07-20,True,True,True,True,2016-07-20
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,...,5964,NaN,2016-07-17,2016-07-17,2016-07-17,True,True,True,True,2016-07-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,...,31,NaN,None,None,None,False,False,False,False,NaN
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,...,30,NaN,None,None,None,False,False,False,False,NaN
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,29,NaN,None,None,None,False,False,False,False,NaN
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,...,28,NaN,None,None,None,False,False,False,False,NaN
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,27,NaN,None,None,None,False,False,False,False,NaN
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,...,26,NaN,None,None,None,False,False,False,False,NaN
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,...,25,NaN,None,None,None,False,False,False,False,NaN
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,...,24,NaN,None,None,None,False,False,False,False,NaN
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,...,23,NaN,None,None,None,False,False,False,False,NaN
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,...,22,NaN,None,None,None,False,False,False,False,NaN
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,...,21,NaN,None,None,None,False,False,False,False,NaN
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,...,20,NaN,None,None,None,False,False,False,False,NaN
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng Tàu,Swimming around anchored ship,crewman,M,...,19,NaN,None,None,None,False,False,False,False,NaN
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,18,NaN,None,None,None,False,False,False,False,NaN
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,17,NaN,None,None,None,False,False,False,False,NaN
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,16,NaN,None,None,None,False,False,False,False,NaN
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,15,NaN,None,None,None,False,False,False,False,NaN
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,...,14,NaN,None,None,None,False,False,False,False,NaN
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,...,13,NaN,None,None,None,False,False,False,False,NaN
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,12,NaN,None,None,None,False,False,False,False,NaN
5982,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,A chiefess,F,...,11,NaN,None,None,None,False,False,False,False,NaN
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,10,NaN,None,None,None,False,False,False,False,NaN
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,9,NaN,None,None,None,False,False,False,False,NaN
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,8,NaN,None,None,None,False,False,False,False,NaN
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,7,NaN,None,None,None,False,False,False,False,NaN
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,6,NaN,None,None,None,False,False,False,False,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,5,NaN,None,None,None,False,False,False,False,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,4,NaN,None,None,None,False,False,False,False,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,3,NaN,None,None,None,False,False,False,False,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,2,NaN,None,None,None,False,False,False,False,NaN

# Clean Unnamed 23:  - Borramos columna por el número de nulls

In [16]:
df[df['unnamed_23'].notnull()]

,case_number,date,year,type,country,area,location,activity,name,sex,...,unnamed_22,unnamed_23,case_number_c,case_number_1_c,case_number_2_c,match_all_date,match_1,match_2,match_3,date_c
4182,1952.07.13,13-Jul-52,1952,Provoked,USA,California,"San Diego, San Diego County",Fishing,"Gerald Howard, on board sportsfishing boat Ter...",M,...,NaN,Teramo,1952-07-13,1952-07-13,1952-07-13,True,True,True,True,1952-07-13
5585,1879.03.10,10-Mar-1879,1879,Invalid,AUSTRALIA,New South Wales,Near Sydney,The steamship Bonnie Dundee lost in collision,Cabin boy of the Bonnie Dundee,M,...,NaN,change filename,1879-03-10,1879-03-10,1879-03-10,True,True,True,True,1879-03-10

In [17]:
df.drop(['unnamed_23'], axis=1)

,case_number,date,year,type,country,area,location,activity,name,sex,...,original_order,unnamed_22,case_number_c,case_number_1_c,case_number_2_c,match_all_date,match_1,match_2,match_3,date_c
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5993,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,5992,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5991,NaN,2016-09-18,2016-09-18,2016-09-18,True,True,True,True,2016-09-18
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,5990,NaN,2016-09-17,2016-09-17,2016-09-17,True,True,True,True,2016-09-17
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,5989,NaN,2016-09-15,2016-09-16,2016-09-15,False,False,False,True,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,5988,NaN,2016-09-15,2016-09-15,2016-09-15,True,True,True,True,2016-09-15
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,5987,NaN,2016-09-11,2016-09-11,2016-09-11,True,True,True,True,2016-09-11
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,5986,NaN,2016-09-07,2016-09-07,2016-09-07,True,True,True,True,2016-09-07
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,5985,NaN,2016-09-06,2016-09-06,2016-09-06,True,True,True,True,2016-09-06
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,5984,NaN,2016-09-05,2016-09-05,2016-09-05,True,True,True,True,2016-09-05
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,5983,NaN,2016-09-05,2016-09-05,2016-09-05,True,True,True,True,2016-09-05
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,5982,NaN,2016-09-04,2016-09-04,2016-09-04,True,True,True,True,2016-09-04
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,5981,NaN,2016-09-01,2016-09-01,2016-09-01,True,True,True,True,2016-09-01
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,5980,NaN,2016-08-29,2016-08-29,2016-08-29,True,True,True,True,2016-08-29
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,5979,NaN,2016-08-29,2016-08-29,2016-08-29,True,True,True,True,2016-08-29
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,5978,NaN,2016-08-27,2016-08-27,2016-08-27,True,True,True,True,2016-08-27
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,5977,NaN,2016-08-25,2016-08-25,2016-08-25,True,True,True,True,2016-08-25
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,5976,NaN,2016-08-07,2016-08-07,2016-08-07,True,True,True,True,2016-08-07
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,5975,NaN,2016-08-06,2016-08-06,2016-08-06,True,True,True,True,2016-08-06
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,5974,NaN,2016-08-04,2016-08-04,2016-08-04,True,True,True,True,2016-08-04
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,...,5973,NaN,2016-07-29,2016-07-29,2016-07-29,True,True,True,True,2016-07-29
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,...,5972,NaN,2016-07-28,2016-07-28,2016-07-28,True,True,True,True,2016-07-28
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,...,5971,NaN,2016-07-28,2016-07-28,2016-07-28,True,True,True,True,2016-07-28
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,...,5970,NaN,2016-07-27,2016-07-27,2016-07-27,True,True,True,True,2016-07-27
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,...,5969,NaN,2016-07-26,2016-07-26,2016-07-26,True,True,True,True,2016-07-26
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,...,5968,NaN,2016-07-24,2016-07-24,2016-07-24,True,True,True,True,2016-07-24
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,...,5967,NaN,2016-07-23,2016-07-23,2016-07-23,True,True,True,True,2016-07-23
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,...,5966,NaN,2016-07-23,2016-07-23,2016-07-23,True,True,True,True,2016-07-23
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,...,5965,NaN,2016-07-20,2016-07-20,2016-07-20,True,True,True,True,2016-07-20
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,...,5964,NaN,2016-07-17,2016-07-17,2016-07-17,True,True,True,True,2016-07-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,...,31,NaN,None,None,None,False,False,False,False,NaN
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,...,30,NaN,None,None,None,False,False,False,False,NaN
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,29,NaN,None,None,None,False,False,False,False,NaN
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,...,28,NaN,None,None,None,False,False,False,False,NaN
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,27,NaN,None,None,None,False,False,False,False,NaN
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,...,26,NaN,None,None,None,False,False,False,False,NaN
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,...,25,NaN,None,None,None,False,False,False,False,NaN
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,...,24,NaN,None,None,None,False,False,False,False,NaN
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,...,23,NaN,None,None,None,False,False,False,False,NaN
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,...,22,NaN,None,None,None,False,False,False,False,NaN
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,...,21,NaN,None,None,None,False,False,False,False,NaN
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,...,20,NaN,None,None,None,False,False,False,False,NaN
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng Tàu,Swimming around anchored ship,crewman,M,...,19,NaN,None,None,None,False,False,False,False,NaN
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,18,NaN,None,None,None,False,False,False,False,NaN
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,17,NaN,None,None,None,False,False,False,False,NaN
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,16,NaN,None,None,None,False,False,False,False,NaN
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,15,NaN,None,None,None,False,False,False,False,NaN
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,...,14,NaN,None,None,None,False,False,False,False,NaN
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,...,13,NaN,None,None,None,False,False,False,False,NaN
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,12,NaN,None,None,None,False,False,False,False,NaN
5982,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,A chiefess,F,...,11,NaN,None,None,None,False,False,False,False,NaN
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,10,NaN,None,None,None,False,False,False,False,NaN
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,9,NaN,None,None,None,False,False,False,False,NaN
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,8,NaN,None,None,None,False,False,False,False,NaN
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,7,NaN,None,None,None,False,False,False,False,NaN
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,6,NaN,None,None,None,False,False,False,False,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,5,NaN,None,None,None,False,False,False,False,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,4,NaN,None,None,None,False,False,False,False,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,3,NaN,None,None,None,False,False,False,False,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,2,NaN,None,None,None,False,False,False,False,NaN

# Clean sex: Aplicamos una función para limpiar los valores inválidos (NA=No aplica)

In [18]:
def clean_sex(sex):
    sex=sex.strip()
    if((sex=='M') | (sex=='F')):
        clean_sex=sex
    elif(sex=='nan' or not sex):
        clean_sex = None
    else:
        clean_sex ='NA'
    return(clean_sex)

df['sex_c']= df.sex.apply(lambda x:clean_sex(str(x)));

In [19]:
df['sex_c'].value_counts()

M     4837
F      585
NA       3
Name: sex_c, dtype: int64

# Clean age

## Vemos los counts, hay de todo, tomaremos solamente los valores que sean enteros y válidos

In [20]:
df['age'].value_counts()

17                148
18                145
19                138
20                136
15                135
16                134
21                115
22                113
24                103
25                101
14                 97
13                 91
23                 80
26                 80
27                 78
28                 77
29                 75
30                 74
12                 70
32                 64
35                 64
10                 51
31                 50
40                 50
38                 47
34                 45
43                 43
36                 41
33                 40
37                 37
                 ...
mid-20s             1
84                  1
33 or 37            1
36 & 23             1
>50                 1
33 & 37             1
46 & 34             1
16 to 18            1
21, 34,24 & 35      1
30 & 32             1
50 & 30             1
31 or 33            1
60's                1
18 or 20            1
"young"             1
32 & 30             1
18 to 22            1
mid-30s             1
12 or 13            1
30 or 36            1
Both 11             1
33 & 26             1
X                   1
60s                 1
23 & 20             1
17 & 16             1
18 months           1
72                  1
(adult)             1
9 or 10             1
Name: age, Length: 151, dtype: int64

## Aplicamos dos funciones, una para verificar que la edad es un número y otra para convertir el campo a integer

In [21]:
def is_number(age):
    try:
        age=age.strip()
        int(age)
        return True
    except ValueError:
        return False

def clean_age(age):
    if is_number(age)==True:
        return(int(age))
    else:
        return None

df['age_is_valid_value'] = df['age'].fillna(-1)
df['age_is_valid_value']= df.age_is_valid_value.apply(lambda x:is_number(str(x)))

df['age_c']= df.age.apply(lambda x:clean_age(str(x)))

In [22]:
print(df['age_is_valid_value'].value_counts())

True     5891
False     101
Name: age_is_valid_value, dtype: int64

In [23]:
print(df['age_c'].value_counts())

17.0    148
18.0    145
19.0    138
20.0    136
15.0    135
16.0    134
21.0    115
22.0    113
24.0    103
25.0    101
14.0     97
13.0     91
23.0     80
26.0     80
27.0     78
28.0     77
29.0     75
30.0     74
12.0     70
32.0     64
35.0     64
10.0     51
31.0     50
40.0     50
38.0     47
34.0     45
43.0     43
36.0     41
33.0     40
39.0     37
       ...
57.0     14
54.0     14
53.0     13
58.0     12
59.0     11
61.0     11
63.0      9
56.0      9
69.0      8
62.0      8
5.0       7
70.0      6
68.0      6
3.0       4
65.0      4
64.0      4
71.0      3
66.0      3
77.0      3
75.0      2
74.0      2
78.0      2
1.0       2
73.0      1
72.0      1
84.0      1
87.0      1
67.0      1
86.0      1
81.0      1
Name: age_c, Length: 79, dtype: int64

# Clean Type

In [24]:
df['type']=df['type'].astype(str).str.strip()

In [25]:
df['type'].value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: type, dtype: int64

In [26]:
def clean_type(typo):
    return('Boating' if typo.strip().startswith('Boat') else typo.strip())
    
df['type_c']=df.type.apply(lambda x:clean_type(x));

In [27]:
df['type_c'].value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Boating          310
Sea Disaster     220
Name: type_c, dtype: int64

# Clean Activity

## Vemos los valores, en un intento para categorizarlos vemos que la mayoría de las actividades tienen el verbo terminando en ing

In [28]:
df['activity'].value_counts()

Surfing                                                                             904
Swimming                                                                            819
Fishing                                                                             414
Spearfishing                                                                        321
Bathing                                                                             153
Wading                                                                              144
Diving                                                                              123
Standing                                                                             97
Snorkeling                                                                           77
Scuba diving                                                                         74
Body boarding                                                                        54
Body surfing                                                                         48
Swimming                                                                             47
Treading water                                                                       32
Pearl diving                                                                         32
Kayaking                                                                             28
Boogie boarding                                                                      28
Free diving                                                                          26
Fell overboard                                                                       21
Windsurfing                                                                          18
Boogie Boarding                                                                      16
Walking                                                                              15
Shark fishing                                                                        15
Canoeing                                                                             12
Surf-skiing                                                                          12
Rowing                                                                               12
Floating                                                                             12
Fishing                                                                              12
Surf skiing                                                                          12
Surf fishing                                                                         11
                                                                                   ...
Ship lay at anchor & man was working on its rudder                                    1
Standing, washing rear wheels of his ambulance in ankle-deep water                    1
Helmet diving, collecting trochus shell                                               1
Slipped off rocks and fell into the water                                             1
                                                                                      1
Diving, recovering fish killed by dynamite                                            1
Swimming (lead swimmer in race)                                                       1
Swimming to anchored boat                                                             1
Swimming to shore from capsized kayak                                                 1
Swimming with fish attached to  belt                                                  1
Standing / Bathing                                                                    1
Diving / Filming                                                                      1
Hooking into a whale                                                                  1
Towing her sister on plastic ski board                                                1
Bathing in 2 feet of water                                                            1
Fishing for white sharks                                                              1
Net-fishing                                                                           1
Testing movie camera in full diving dress                                             1
Swimming in the channel                                                               1
Ditched plane in the sea & were adrift on a rubber life raft.                         1
Searching for remains of  Dr. Marais                                                  1
Crossing inlet in a boat, seen fighting sharks with his oar, sharks smashed boat      1
Murder victim                                                                         1
Splashing / wading                                                                    1
Fishing, standing in waist-deep water                                                 1
Yacht of Michael Howell capsized                                                      1
Treading water, waiting for a wave                                                    1
Diving / UW photography                                                               1
Swimming, after boat swamped                                                          1
Lost his footing & fell overboard                                                     1
Name: activity, Length: 1492, dtype: int64

## Categorizamos la variable activity, sin embargo no eliminamos en este caso la descripción

In [29]:
def clean_activity(activity):
    new_activity = re.sub(r'[^\w\s]',' ',activity)
    clean_activity= [str.lower(w) for w in activity.split() if w.endswith('ing')]
    return(clean_activity)
    
df['activity_c'] = df.activity.apply(lambda x:clean_activity(str(x)))

## Si comparamos con los valores originales, ganamos algo. Vemos los valores hay más de una categoría, no hay tiempo, pero se puede sacar este array a otra tabla+el original order

In [32]:
df['activity'].value_counts()

Surfing                                                                             904
Swimming                                                                            819
Fishing                                                                             414
Spearfishing                                                                        321
Bathing                                                                             153
Wading                                                                              144
Diving                                                                              123
Standing                                                                             97
Snorkeling                                                                           77
Scuba diving                                                                         74
Body boarding                                                                        54
Body surfing                                                                         48
Swimming                                                                             47
Treading water                                                                       32
Pearl diving                                                                         32
Kayaking                                                                             28
Boogie boarding                                                                      28
Free diving                                                                          26
Fell overboard                                                                       21
Windsurfing                                                                          18
Boogie Boarding                                                                      16
Walking                                                                              15
Shark fishing                                                                        15
Canoeing                                                                             12
Surf-skiing                                                                          12
Rowing                                                                               12
Floating                                                                             12
Fishing                                                                              12
Surf skiing                                                                          12
Surf fishing                                                                         11
                                                                                   ...
Ship lay at anchor & man was working on its rudder                                    1
Standing, washing rear wheels of his ambulance in ankle-deep water                    1
Helmet diving, collecting trochus shell                                               1
Slipped off rocks and fell into the water                                             1
                                                                                      1
Diving, recovering fish killed by dynamite                                            1
Swimming (lead swimmer in race)                                                       1
Swimming to anchored boat                                                             1
Swimming to shore from capsized kayak                                                 1
Swimming with fish attached to  belt                                                  1
Standing / Bathing                                                                    1
Diving / Filming                                                                      1
Hooking into a whale                                                                  1
Towing her sister on plastic ski board                                                1
Bathing in 2 feet of water                                                            1
Fishing for white sharks                                                              1
Net-fishing                                                                           1
Testing movie camera in full diving dress                                             1
Swimming in the channel                                                               1
Ditched plane in the sea & were adrift on a rubber life raft.                         1
Searching for remains of  Dr. Marais                                                  1
Crossing inlet in a boat, seen fighting sharks with his oar, sharks smashed boat      1
Murder victim                                                                         1
Splashing / wading                                                                    1
Fishing, standing in waist-deep water                                                 1
Yacht of Michael Howell capsized                                                      1
Treading water, waiting for a wave                                                    1
Diving / UW photography                                                               1
Swimming, after boat swamped                                                          1
Lost his footing & fell overboard                                                     1
Name: activity, Length: 1492, dtype: int64

In [33]:
df['activity_c'].value_counts()

[swimming]                       986
[surfing]                        975
[]                               963
[fishing]                        615
[diving]                         434
[spearfishing]                   350
[bathing]                        173
[wading]                         150
[standing]                       121
[boarding]                       116
[snorkeling]                      78
[floating]                        42
[treading]                        37
[kayaking]                        30
[attempting]                      27
[playing]                         22
[sitting]                         22
[skiing]                          21
[rowing]                          20
[walking]                         20
[windsurfing]                     18
[paddling]                        18
[collecting]                      17
[diving, spearfishing]            15
[spearfishing, diving]            14
[canoeing]                        13
[sailing]                         13
[freediving]                      13
[surf-skiing]                     12
[netting]                         12
                                ...
[checking]                         1
[swimming, jumping]                1
[using]                            1
[shrimping]                        1
[taking, swimming]                 1
[diving, modeling]                 1
[chasing, bathing, riding]         1
[diving, kissing]                  1
[lining]                           1
[diving, kneeling]                 1
[holding, dangling]                1
[pushing]                          1
[wading, string]                   1
[lashing]                          1
[seining, standing]                1
[paddle-boarding]                  1
[loading, bathing]                 1
[fishing, standing]                1
[ascending]                        1
[paddle-surfing]                   1
[fishing, basking]                 1
[crawling]                         1
[fishing, spearfishing]            1
[net-fishing]                      1
[abandoning, burning, raging]      1
[fishing, holding]                 1
[missing, bailing]                 1
[swimming, washing, cooking]       1
[testing, diving]                  1
[during, filming]                  1
Name: activity_c, Length: 373, dtype: int64

# Clean country

## Haremos la primera búsqueda con la librería country_converter

In [37]:
cc = coco.CountryConverter()

df['country_c']=df.country.apply(lambda x: cc.convert(names = x, to = 'name_short'))

WARNING:root:COLUMBIA not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:DIEGO GARCIA not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:AZORES not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:AZORES not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:GULF OF ADEN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ST. MAARTIN not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL

WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:More then one regular expression match for EGYPT / ISRAEL
WARNING:root:NORTHERN ARABIAN SEA not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:NORTH ATLANTIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN  not found in regex
WARNING:root:BRITISH ISLES not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:JOHNSTON ISLAND not found in regex
WARNING:root:PACIFIC OCEAN  not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:SOUTH PACIFIC OCEAN not found in regex
WARNING:root:RED SEA not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:MID ATLANTIC OCEAN not found in regex
WARNING:root:ADMIRALTY ISLANDS not found in regex
WARNING:root:BRITISH WEST INDIES not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:MID ATLANTIC OCEAN not found in regex
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:RED SEA / INDIAN OCEAN not found in regex
WARNING:root:JOHNSTON ISLAND not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:NORTH SEA not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:AZORES not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:NORTH ATLANTIC OCEAN not found in regex
WARNING:root:MID ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ANDAMAN / NICOBAR ISLANDAS not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:MID ATLANTIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:NORTH ATLANTIC OCEAN  not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:THE BALKANS not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:NETHERLANDS ANTILLES not found in regex
WARNING:root:NORTH ATLANTIC OCEAN not found in regex
WARNING:root:COLUMBIA not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:MID ATLANTIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ

WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:More then one regular expression match for IRAN / IRAQ
WARNING:root:JAVA not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:SOUTH PACIFIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:CENTRAL PACIFIC not found in regex
WARNING:root:CENTRAL PACIFIC not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU

WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:More then one regular expression match for SOLOMON ISLANDS / VANUATU
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:SOUTHWEST PACIFIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:BAY OF BENGAL not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:MID-PACIFC OCEAN not found in regex
WARNING:root:SOUTHWEST PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:SCOTLAND not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA

WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:More then one regular expression match for ITALY / CROATIA
WARNING:root:nan not found in ISO3
WARNING:root:AZORES not found in regex
WARNING:root:OKINAWA not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:SAN DOMINGO not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:NORTH ATLANTIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:MEDITERRANEAN SEA? not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:CRETE not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:CRETE not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:INDIAN OCEAN not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:INDIAN OCEAN? not found in regex
WARNING:root:AZORES not found in regex
WARNING:root:SOUTH ATLANTIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:SCOTLAND not found in regex
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON

WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON

WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:More then one regular expression match for EQUATORIAL GUINEA / CAMEROON
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:ATLANTIC OCEAN not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:Coast of AFRICA not found in regex
WARNING:root:TASMAN SEA not found in regex
WARNING:root:CARIBBEAN SEA not found in regex
WARNING:root:ENGLAND not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:ENGLAND not found in regex
WARNING:root:MEDITERRANEAN SEA not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA

WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:More then one regular expression match for Between PORTUGAL & INDIA
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:nan not found in ISO3
WARNING:root:BAHREIN not found in regex
WARNING:root:RED SEA? not found in regex
WARNING:root:MEDITERRANEAN SEA not found in regex
WARNING:root:NORTH PACIFIC OCEAN not found in regex
WARNING:root:nan not found in ISO3
WARNING:root:PACIFIC OCEAN not found in regex
WARNING:root:ASIA? not found in regex

## Haremos una segunda búsqueda con la librería pycountry, que tiene todas los paises en una lista

In [36]:
list(pycountry.countries)

[Country(alpha_2='AW', alpha_3='ABW', name='Aruba', numeric='533'),
 Country(alpha_2='AF', alpha_3='AFG', name='Afghanistan', numeric='004', official_name='Islamic Republic of Afghanistan'),
 Country(alpha_2='AO', alpha_3='AGO', name='Angola', numeric='024', official_name='Republic of Angola'),
 Country(alpha_2='AI', alpha_3='AIA', name='Anguilla', numeric='660'),
 Country(alpha_2='AX', alpha_3='ALA', name='Åland Islands', numeric='248'),
 Country(alpha_2='AL', alpha_3='ALB', name='Albania', numeric='008', official_name='Republic of Albania'),
 Country(alpha_2='AD', alpha_3='AND', name='Andorra', numeric='020', official_name='Principality of Andorra'),
 Country(alpha_2='AE', alpha_3='ARE', name='United Arab Emirates', numeric='784'),
 Country(alpha_2='AR', alpha_3='ARG', name='Argentina', numeric='032', official_name='Argentine Republic'),
 Country(alpha_2='AM', alpha_3='ARM', name='Armenia', numeric='051', official_name='Republic of Armenia'),
 Country(alpha_2='AS', alpha_3='ASM', name='American Samoa', numeric='016'),
 Country(alpha_2='AQ', alpha_3='ATA', name='Antarctica', numeric='010'),
 Country(alpha_2='TF', alpha_3='ATF', name='French Southern Territories', numeric='260'),
 Country(alpha_2='AG', alpha_3='ATG', name='Antigua and Barbuda', numeric='028'),
 Country(alpha_2='AU', alpha_3='AUS', name='Australia', numeric='036'),
 Country(alpha_2='AT', alpha_3='AUT', name='Austria', numeric='040', official_name='Republic of Austria'),
 Country(alpha_2='AZ', alpha_3='AZE', name='Azerbaijan', numeric='031', official_name='Republic of Azerbaijan'),
 Country(alpha_2='BI', alpha_3='BDI', name='Burundi', numeric='108', official_name='Republic of Burundi'),
 Country(alpha_2='BE', alpha_3='BEL', name='Belgium', numeric='056', official_name='Kingdom of Belgium'),
 Country(alpha_2='BJ', alpha_3='BEN', name='Benin', numeric='204', official_name='Republic of Benin'),
 Country(alpha_2='BQ', alpha_3='BES', name='Bonaire, Sint Eustatius and Saba', numeric='535', official_name='Bonaire, Sint Eustatius and Saba'),
 Country(alpha_2='BF', alpha_3='BFA', name='Burkina Faso', numeric='854'),
 Country(alpha_2='BD', alpha_3='BGD', name='Bangladesh', numeric='050', official_name="People's Republic of Bangladesh"),
 Country(alpha_2='BG', alpha_3='BGR', name='Bulgaria', numeric='100', official_name='Republic of Bulgaria'),
 Country(alpha_2='BH', alpha_3='BHR', name='Bahrain', numeric='048', official_name='Kingdom of Bahrain'),
 Country(alpha_2='BS', alpha_3='BHS', name='Bahamas', numeric='044', official_name='Commonwealth of the Bahamas'),
 Country(alpha_2='BA', alpha_3='BIH', name='Bosnia and Herzegovina', numeric='070', official_name='Republic of Bosnia and Herzegovina'),
 Country(alpha_2='BL', alpha_3='BLM', name='Saint Barthélemy', numeric='652'),
 Country(alpha_2='BY', alpha_3='BLR', name='Belarus', numeric='112', official_name='Republic of Belarus'),
 Country(alpha_2='BZ', alpha_3='BLZ', name='Belize', numeric='084'),
 Country(alpha_2='BM', alpha_3='BMU', name='Bermuda', numeric='060'),
 Country(alpha_2='BO', alpha_3='BOL', common_name='Bolivia', name='Bolivia, Plurinational State of', numeric='068', official_name='Plurinational State of Bolivia'),
 Country(alpha_2='BR', alpha_3='BRA', name='Brazil', numeric='076', official_name='Federative Republic of Brazil'),
 Country(alpha_2='BB', alpha_3='BRB', name='Barbados', numeric='052'),
 Country(alpha_2='BN', alpha_3='BRN', name='Brunei Darussalam', numeric='096'),
 Country(alpha_2='BT', alpha_3='BTN', name='Bhutan', numeric='064', official_name='Kingdom of Bhutan'),
 Country(alpha_2='BV', alpha_3='BVT', name='Bouvet Island', numeric='074'),
 Country(alpha_2='BW', alpha_3='BWA', name='Botswana', numeric='072', official_name='Republic of Botswana'),
 Country(alpha_2='CF', alpha_3='CAF', name='Central African Republic', numeric='140'),
 Country(alpha_2='CA', alpha_3='CAN', name='Canada', numeric='124'),
 Country(alpha_2='CC', alpha_3='CCK', name='Cocos (Keeling) Islands', numeric='166'),
 Country(alpha_2='CH', alpha_3='CHE', name='Switzerland', numeric='756', official_name='Swiss Confederation'),
 Country(alpha_2='CL', alpha_3='CHL', name='Chile', numeric='152', official_name='Republic of Chile'),
 Country(alpha_2='CN', alpha_3='CHN', name='China', numeric='156', official_name="People's Republic of China"),
 Country(alpha_2='CI', alpha_3='CIV', name="Côte d'Ivoire", numeric='384', official_name="Republic of Côte d'Ivoire"),
 Country(alpha_2='CM', alpha_3='CMR', name='Cameroon', numeric='120', official_name='Republic of Cameroon'),
 Country(alpha_2='CD', alpha_3='COD', name='Congo, The Democratic Republic of the', numeric='180'),
 Country(alpha_2='CG', alpha_3='COG', name='Congo', numeric='178', official_name='Republic of the Congo'),
 Country(alpha_2='CK', alpha_3='COK', name='Cook Islands', numeric='184'),
 Country(alpha_2='CO', alpha_3='COL', name='Colombia', numeric='170', official_name='Republic of Colombia'),
 Country(alpha_2='KM', alpha_3='COM', name='Comoros', numeric='174', official_name='Union of the Comoros'),
 Country(alpha_2='CV', alpha_3='CPV', name='Cabo Verde', numeric='132', official_name='Republic of Cabo Verde'),
 Country(alpha_2='CR', alpha_3='CRI', name='Costa Rica', numeric='188', official_name='Republic of Costa Rica'),
 Country(alpha_2='CU', alpha_3='CUB', name='Cuba', numeric='192', official_name='Republic of Cuba'),
 Country(alpha_2='CW', alpha_3='CUW', name='Curaçao', numeric='531', official_name='Curaçao'),
 Country(alpha_2='CX', alpha_3='CXR', name='Christmas Island', numeric='162'),
 Country(alpha_2='KY', alpha_3='CYM', name='Cayman Islands', numeric='136'),
 Country(alpha_2='CY', alpha_3='CYP', name='Cyprus', numeric='196', official_name='Republic of Cyprus'),
 Country(alpha_2='CZ', alpha_3='CZE', name='Czechia', numeric='203', official_name='Czech Republic'),
 Country(alpha_2='DE', alpha_3='DEU', name='Germany', numeric='276', official_name='Federal Republic of Germany'),
 Country(alpha_2='DJ', alpha_3='DJI', name='Djibouti', numeric='262', official_name='Republic of Djibouti'),
 Country(alpha_2='DM', alpha_3='DMA', name='Dominica', numeric='212', official_name='Commonwealth of Dominica'),
 Country(alpha_2='DK', alpha_3='DNK', name='Denmark', numeric='208', official_name='Kingdom of Denmark'),
 Country(alpha_2='DO', alpha_3='DOM', name='Dominican Republic', numeric='214'),
 Country(alpha_2='DZ', alpha_3='DZA', name='Algeria', numeric='012', official_name="People's Democratic Republic of Algeria"),
 Country(alpha_2='EC', alpha_3='ECU', name='Ecuador', numeric='218', official_name='Republic of Ecuador'),
 Country(alpha_2='EG', alpha_3='EGY', name='Egypt', numeric='818', official_name='Arab Republic of Egypt'),
 Country(alpha_2='ER', alpha_3='ERI', name='Eritrea', numeric='232', official_name='the State of Eritrea'),
 Country(alpha_2='EH', alpha_3='ESH', name='Western Sahara', numeric='732'),
 Country(alpha_2='ES', alpha_3='ESP', name='Spain', numeric='724', official_name='Kingdom of Spain'),
 Country(alpha_2='EE', alpha_3='EST', name='Estonia', numeric='233', official_name='Republic of Estonia'),
 Country(alpha_2='ET', alpha_3='ETH', name='Ethiopia', numeric='231', official_name='Federal Democratic Republic of Ethiopia'),
 Country(alpha_2='FI', alpha_3='FIN', name='Finland', numeric='246', official_name='Republic of Finland'),
 Country(alpha_2='FJ', alpha_3='FJI', name='Fiji', numeric='242', official_name='Republic of Fiji'),
 Country(alpha_2='FK', alpha_3='FLK', name='Falkland Islands (Malvinas)', numeric='238'),
 Country(alpha_2='FR', alpha_3='FRA', name='France', numeric='250', official_name='French Republic'),
 Country(alpha_2='FO', alpha_3='FRO', name='Faroe Islands', numeric='234'),
 Country(alpha_2='FM', alpha_3='FSM', name='Micronesia, Federated States of', numeric='583', official_name='Federated States of Micronesia'),
 Country(alpha_2='GA', alpha_3='GAB', name='Gabon', numeric='266', official_name='Gabonese Republic'),
 Country(alpha_2='GB', alpha_3='GBR', name='United Kingdom', numeric='826', official_name='United Kingdom of Great Britain and Northern Ireland'),
 Country(alpha_2='GE', alpha_3='GEO', name='Georgia', numeric='268'),
 Country(alpha_2='GG', alpha_3='GGY', name='Guernsey', numeric='831'),
 Country(alpha_2='GH', alpha_3='GHA', name='Ghana', numeric='288', official_name='Republic of Ghana'),
 Country(alpha_2='GI', alpha_3='GIB', name='Gibraltar', numeric='292'),
 Country(alpha_2='GN', alpha_3='GIN', name='Guinea', numeric='324', official_name='Republic of Guinea'),
 Country(alpha_2='GP', alpha_3='GLP', name='Guadeloupe', numeric='312'),
 Country(alpha_2='GM', alpha_3='GMB', name='Gambia', numeric='270', official_name='Republic of the Gambia'),
 Country(alpha_2='GW', alpha_3='GNB', name='Guinea-Bissau', numeric='624', official_name='Republic of Guinea-Bissau'),
 Country(alpha_2='GQ', alpha_3='GNQ', name='Equatorial Guinea', numeric='226', official_name='Republic of Equatorial Guinea'),
 Country(alpha_2='GR', alpha_3='GRC', name='Greece', numeric='300', official_name='Hellenic Republic'),
 Country(alpha_2='GD', alpha_3='GRD', name='Grenada', numeric='308'),
 Country(alpha_2='GL', alpha_3='GRL', name='Greenland', numeric='304'),
 Country(alpha_2='GT', alpha_3='GTM', name='Guatemala', numeric='320', official_name='Republic of Guatemala'),
 Country(alpha_2='GF', alpha_3='GUF', name='French Guiana', numeric='254'),
 Country(alpha_2='GU', alpha_3='GUM', name='Guam', numeric='316'),
 Country(alpha_2='GY', alpha_3='GUY', name='Guyana', numeric='328', official_name='Republic of Guyana'),
 Country(alpha_2='HK', alpha_3='HKG', name='Hong Kong', numeric='344', official_name='Hong Kong Special Administrative Region of China'),
 Country(alpha_2='HM', alpha_3='HMD', name='Heard Island and McDonald Islands', numeric='334'),
 Country(alpha_2='HN', alpha_3='HND', name='Honduras', numeric='340', official_name='Republic of Honduras'),
 Country(alpha_2='HR', alpha_3='HRV', name='Croatia', numeric='191', official_name='Republic of Croatia'),
 Country(alpha_2='HT', alpha_3='HTI', name='Haiti', numeric='332', official_name='Republic of Haiti'),
 Country(alpha_2='HU', alpha_3='HUN', name='Hungary', numeric='348', official_name='Hungary'),
 Country(alpha_2='ID', alpha_3='IDN', name='Indonesia', numeric='360', official_name='Republic of Indonesia'),
 Country(alpha_2='IM', alpha_3='IMN', name='Isle of Man', numeric='833'),
 Country(alpha_2='IN', alpha_3='IND', name='India', numeric='356', official_name='Republic of India'),
 Country(alpha_2='IO', alpha_3='IOT', name='British Indian Ocean Territory', numeric='086'),
 Country(alpha_2='IE', alpha_3='IRL', name='Ireland', numeric='372'),
 Country(alpha_2='IR', alpha_3='IRN', name='Iran, Islamic Republic of', numeric='364', official_name='Islamic Republic of Iran'),
 Country(alpha_2='IQ', alpha_3='IRQ', name='Iraq', numeric='368', official_name='Republic of Iraq'),
 Country(alpha_2='IS', alpha_3='ISL', name='Iceland', numeric='352', official_name='Republic of Iceland'),
 Country(alpha_2='IL', alpha_3='ISR', name='Israel', numeric='376', official_name='State of Israel'),
 Country(alpha_2='IT', alpha_3='ITA', name='Italy', numeric='380', official_name='Italian Republic'),
 Country(alpha_2='JM', alpha_3='JAM', name='Jamaica', numeric='388'),
 Country(alpha_2='JE', alpha_3='JEY', name='Jersey', numeric='832'),
 Country(alpha_2='JO', alpha_3='JOR', name='Jordan', numeric='400', official_name='Hashemite Kingdom of Jordan'),
 Country(alpha_2='JP', alpha_3='JPN', name='Japan', numeric='392'),
 Country(alpha_2='KZ', alpha_3='KAZ', name='Kazakhstan', numeric='398', official_name='Republic of Kazakhstan'),
 Country(alpha_2='KE', alpha_3='KEN', name='Kenya', numeric='404', official_name='Republic of Kenya'),
 Country(alpha_2='KG', alpha_3='KGZ', name='Kyrgyzstan', numeric='417', official_name='Kyrgyz Republic'),
 Country(alpha_2='KH', alpha_3='KHM', name='Cambodia', numeric='116', official_name='Kingdom of Cambodia'),
 Country(alpha_2='KI', alpha_3='KIR', name='Kiribati', numeric='296', official_name='Republic of Kiribati'),
 Country(alpha_2='KN', alpha_3='KNA', name='Saint Kitts and Nevis', numeric='659'),
 Country(alpha_2='KR', alpha_3='KOR', name='Korea, Republic of', numeric='410'),
 Country(alpha_2='KW', alpha_3='KWT', name='Kuwait', numeric='414', official_name='State of Kuwait'),
 Country(alpha_2='LA', alpha_3='LAO', name="Lao People's Democratic Republic", numeric='418'),
 Country(alpha_2='LB', alpha_3='LBN', name='Lebanon', numeric='422', official_name='Lebanese Republic'),
 Country(alpha_2='LR', alpha_3='LBR', name='Liberia', numeric='430', official_name='Republic of Liberia'),
 Country(alpha_2='LY', alpha_3='LBY', name='Libya', numeric='434', official_name='Libya'),
 Country(alpha_2='LC', alpha_3='LCA', name='Saint Lucia', numeric='662'),
 Country(alpha_2='LI', alpha_3='LIE', name='Liechtenstein', numeric='438', official_name='Principality of Liechtenstein'),
 Country(alpha_2='LK', alpha_3='LKA', name='Sri Lanka', numeric='144', official_name='Democratic Socialist Republic of Sri Lanka'),
 Country(alpha_2='LS', alpha_3='LSO', name='Lesotho', numeric='426', official_name='Kingdom of Lesotho'),
 Country(alpha_2='LT', alpha_3='LTU', name='Lithuania', numeric='440', official_name='Republic of Lithuania'),
 Country(alpha_2='LU', alpha_3='LUX', name='Luxembourg', numeric='442', official_name='Grand Duchy of Luxembourg'),
 Country(alpha_2='LV', alpha_3='LVA', name='Latvia', numeric='428', official_name='Republic of Latvia'),
 Country(alpha_2='MO', alpha_3='MAC', name='Macao', numeric='446', official_name='Macao Special Administrative Region of China'),
 Country(alpha_2='MF', alpha_3='MAF', name='Saint Martin (French part)', numeric='663'),
 Country(alpha_2='MA', alpha_3='MAR', name='Morocco', numeric='504', official_name='Kingdom of Morocco'),
 Country(alpha_2='MC', alpha_3='MCO', name='Monaco', numeric='492', official_name='Principality of Monaco'),
 Country(alpha_2='MD', alpha_3='MDA', common_name='Moldova', name='Moldova, Republic of', numeric='498', official_name='Republic of Moldova'),
 Country(alpha_2='MG', alpha_3='MDG', name='Madagascar', numeric='450', official_name='Republic of Madagascar'),
 Country(alpha_2='MV', alpha_3='MDV', name='Maldives', numeric='462', official_name='Republic of Maldives'),
 Country(alpha_2='MX', alpha_3='MEX', name='Mexico', numeric='484', official_name='United Mexican States'),
 Country(alpha_2='MH', alpha_3='MHL', name='Marshall Islands', numeric='584', official_name='Republic of the Marshall Islands'),
 Country(alpha_2='MK', alpha_3='MKD', name='North Macedonia', numeric='807', official_name='Republic of North Macedonia'),
 Country(alpha_2='ML', alpha_3='MLI', name='Mali', numeric='466', official_name='Republic of Mali'),
 Country(alpha_2='MT', alpha_3='MLT', name='Malta', numeric='470', official_name='Republic of Malta'),
 Country(alpha_2='MM', alpha_3='MMR', name='Myanmar', numeric='104', official_name='Republic of Myanmar'),
 Country(alpha_2='ME', alpha_3='MNE', name='Montenegro', numeric='499', official_name='Montenegro'),
 Country(alpha_2='MN', alpha_3='MNG', name='Mongolia', numeric='496'),
 Country(alpha_2='MP', alpha_3='MNP', name='Northern Mariana Islands', numeric='580', official_name='Commonwealth of the Northern Mariana Islands'),
 Country(alpha_2='MZ', alpha_3='MOZ', name='Mozambique', numeric='508', official_name='Republic of Mozambique'),
 Country(alpha_2='MR', alpha_3='MRT', name='Mauritania', numeric='478', official_name='Islamic Republic of Mauritania'),
 Country(alpha_2='MS', alpha_3='MSR', name='Montserrat', numeric='500'),
 Country(alpha_2='MQ', alpha_3='MTQ', name='Martinique', numeric='474'),
 Country(alpha_2='MU', alpha_3='MUS', name='Mauritius', numeric='480', official_name='Republic of Mauritius'),
 Country(alpha_2='MW', alpha_3='MWI', name='Malawi', numeric='454', official_name='Republic of Malawi'),
 Country(alpha_2='MY', alpha_3='MYS', name='Malaysia', numeric='458'),
 Country(alpha_2='YT', alpha_3='MYT', name='Mayotte', numeric='175'),
 Country(alpha_2='NA', alpha_3='NAM', name='Namibia', numeric='516', official_name='Republic of Namibia'),
 Country(alpha_2='NC', alpha_3='NCL', name='New Caledonia', numeric='540'),
 Country(alpha_2='NE', alpha_3='NER', name='Niger', numeric='562', official_name='Republic of the Niger'),
 Country(alpha_2='NF', alpha_3='NFK', name='Norfolk Island', numeric='574'),
 Country(alpha_2='NG', alpha_3='NGA', name='Nigeria', numeric='566', official_name='Federal Republic of Nigeria'),
 Country(alpha_2='NI', alpha_3='NIC', name='Nicaragua', numeric='558', official_name='Republic of Nicaragua'),
 Country(alpha_2='NU', alpha_3='NIU', name='Niue', numeric='570', official_name='Niue'),
 Country(alpha_2='NL', alpha_3='NLD', name='Netherlands', numeric='528', official_name='Kingdom of the Netherlands'),
 Country(alpha_2='NO', alpha_3='NOR', name='Norway', numeric='578', official_name='Kingdom of Norway'),
 Country(alpha_2='NP', alpha_3='NPL', name='Nepal', numeric='524', official_name='Federal Democratic Republic of Nepal'),
 Country(alpha_2='NR', alpha_3='NRU', name='Nauru', numeric='520', official_name='Republic of Nauru'),
 Country(alpha_2='NZ', alpha_3='NZL', name='New Zealand', numeric='554'),
 Country(alpha_2='OM', alpha_3='OMN', name='Oman', numeric='512', official_name='Sultanate of Oman'),
 Country(alpha_2='PK', alpha_3='PAK', name='Pakistan', numeric='586', official_name='Islamic Republic of Pakistan'),
 Country(alpha_2='PA', alpha_3='PAN', name='Panama', numeric='591', official_name='Republic of Panama'),
 Country(alpha_2='PN', alpha_3='PCN', name='Pitcairn', numeric='612'),
 Country(alpha_2='PE', alpha_3='PER', name='Peru', numeric='604', official_name='Republic of Peru'),
 Country(alpha_2='PH', alpha_3='PHL', name='Philippines', numeric='608', official_name='Republic of the Philippines'),
 Country(alpha_2='PW', alpha_3='PLW', name='Palau', numeric='585', official_name='Republic of Palau'),
 Country(alpha_2='PG', alpha_3='PNG', name='Papua New Guinea', numeric='598', official_name='Independent State of Papua New Guinea'),
 Country(alpha_2='PL', alpha_3='POL', name='Poland', numeric='616', official_name='Republic of Poland'),
 Country(alpha_2='PR', alpha_3='PRI', name='Puerto Rico', numeric='630'),
 Country(alpha_2='KP', alpha_3='PRK', name="Korea, Democratic People's Republic of", numeric='408', official_name="Democratic People's Republic of Korea"),
 Country(alpha_2='PT', alpha_3='PRT', name='Portugal', numeric='620', official_name='Portuguese Republic'),
 Country(alpha_2='PY', alpha_3='PRY', name='Paraguay', numeric='600', official_name='Republic of Paraguay'),
 Country(alpha_2='PS', alpha_3='PSE', name='Palestine, State of', numeric='275', official_name='the State of Palestine'),
 Country(alpha_2='PF', alpha_3='PYF', name='French Polynesia', numeric='258'),
 Country(alpha_2='QA', alpha_3='QAT', name='Qatar', numeric='634', official_name='State of Qatar'),
 Country(alpha_2='RE', alpha_3='REU', name='Réunion', numeric='638'),
 Country(alpha_2='RO', alpha_3='ROU', name='Romania', numeric='642'),
 Country(alpha_2='RU', alpha_3='RUS', name='Russian Federation', numeric='643'),
 Country(alpha_2='RW', alpha_3='RWA', name='Rwanda', numeric='646', official_name='Rwandese Republic'),
 Country(alpha_2='SA', alpha_3='SAU', name='Saudi Arabia', numeric='682', official_name='Kingdom of Saudi Arabia'),
 Country(alpha_2='SD', alpha_3='SDN', name='Sudan', numeric='729', official_name='Republic of the Sudan'),
 Country(alpha_2='SN', alpha_3='SEN', name='Senegal', numeric='686', official_name='Republic of Senegal'),
 Country(alpha_2='SG', alpha_3='SGP', name='Singapore', numeric='702', official_name='Republic of Singapore'),
 Country(alpha_2='GS', alpha_3='SGS', name='South Georgia and the South Sandwich Islands', numeric='239'),
 Country(alpha_2='SH', alpha_3='SHN', name='Saint Helena, Ascension and Tristan da Cunha', numeric='654'),
 Country(alpha_2='SJ', alpha_3='SJM', name='Svalbard and Jan Mayen', numeric='744'),

## Search-fuzzy busca posibles match con el nombre del país y devuelve una lista

In [35]:
def get_country_code(name):
    try:
        country=pycountry.countries.search_fuzzy(name)
    except LookupError:
        return list()
    return [x.name for x in country]

df['country_c_2']=df.country.apply(lambda x: list(get_country_code(str(x))))

KeyError: "['country_c'] not in index"

## Limpiamos los campos de country que no hacen match

In [41]:
df[['country','country_c','country_c_2']].head(100)

,country,country_c,country_c_2
0,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
1,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
2,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
3,AUSTRALIA,Australia,[Australia]
4,AUSTRALIA,Australia,[Australia]
5,AUSTRALIA,Australia,[Australia]
6,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
7,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
8,NEW CALEDONIA,New Caledonia,[New Caledonia]
9,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
10,AUSTRALIA,Australia,[Australia]
11,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
12,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
13,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
14,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
15,REUNION,Reunion,"[Réunion, France]"
16,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
17,BAHAMAS,Bahamas,[Bahamas]
18,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
19,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
20,SPAIN,Spain,"[Spain, Trinidad and Tobago]"
21,CHINA,China,"[China, Hong Kong, Macao, Nicaragua, Taiwan, P..."
22,AUSTRALIA,Australia,[Australia]
23,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
24,AUSTRALIA,Australia,[Australia]
25,JAPAN,Japan,[Japan]
26,AUSTRALIA,Australia,[Australia]
27,BAHAMAS,Bahamas,[Bahamas]
28,AUSTRALIA,Australia,[Australia]
29,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
...,...,...,...
70,FRENCH POLYNESIA,French Polynesia,[French Polynesia]
71,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
72,NEW CALEDONIA,New Caledonia,[New Caledonia]
73,CAPE VERDE,Cabo Verde,[]
74,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
75,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
76,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
77,AUSTRALIA,Australia,[Australia]
78,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
79,AUSTRALIA,Australia,[Australia]
80,BAHAMAS,Bahamas,[Bahamas]
81,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
82,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
83,Fiji,Fiji,[Fiji]
84,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
85,AUSTRALIA,Australia,[Australia]
86,BRAZIL,Brazil,[Brazil]
87,NEW CALEDONIA,New Caledonia,[New Caledonia]
88,NEW CALEDONIA,New Caledonia,[New Caledonia]
89,DOMINICAN REPUBLIC,Dominican Republic,[Dominican Republic]
90,CAYMAN ISLANDS,Cayman Islands,[Cayman Islands]
91,AUSTRALIA,Australia,[Australia]
92,AUSTRALIA,Australia,[Australia]
93,AUSTRALIA,Australia,[Australia]
94,SOUTH AFRICA,South Africa,[South Africa]
95,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
96,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
97,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."
98,UNITED ARAB EMIRATES,United Arab Emirates,[United Arab Emirates]
99,USA,United States,"[United States, Indonesia, Azerbaijan, Philipp..."

In [47]:
df_Country_drop=df[(df['country_c']=='not found')]
df_Country_drop[['country','country_c','country_c_2']].head(100)

,country,country_c,country_c_2
42,COLUMBIA,not found,"[Canada, United States]"
225,ATLANTIC OCEAN,not found,[]
303,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
432,DIEGO GARCIA,not found,[]
526,SCOTLAND,not found,[United Kingdom]
625,SCOTLAND,not found,[United Kingdom]
678,COLUMBIA,not found,"[Canada, United States]"
690,COLUMBIA,not found,"[Canada, United States]"
752,AZORES,not found,[]
860,SCOTLAND,not found,[United Kingdom]
938,AZORES,not found,[]
990,ENGLAND,not found,[United Kingdom]
1028,SCOTLAND,not found,[United Kingdom]
1152,ENGLAND,not found,[United Kingdom]
1202,GULF OF ADEN,not found,[]
1282,ATLANTIC OCEAN,not found,[]
1284,ATLANTIC OCEAN,not found,[]
1293,ATLANTIC OCEAN,not found,[]
1310,ST. MAARTIN,not found,[]
1749,CARIBBEAN SEA,not found,[]
1783,OKINAWA,not found,[Japan]
1849,ENGLAND,not found,[United Kingdom]
2020,OKINAWA,not found,[Japan]
2050,OKINAWA,not found,[Japan]
2066,OKINAWA,not found,[Japan]
2106,NORTHERN ARABIAN SEA,not found,[]
2286,CARIBBEAN SEA,not found,[]
2731,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
2799,ENGLAND,not found,[United Kingdom]
2854,NORTH ATLANTIC OCEAN,not found,[]
...,...,...,...
3861,NORTH ATLANTIC OCEAN,not found,[]
3871,MID ATLANTIC OCEAN,not found,[]
3896,ATLANTIC OCEAN,not found,[]
3914,ANDAMAN / NICOBAR ISLANDAS,not found,[]
3924,PACIFIC OCEAN,not found,[]
3925,PACIFIC OCEAN,not found,[]
3961,PACIFIC OCEAN,not found,[]
4005,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
4026,MID ATLANTIC OCEAN,not found,[]
4040,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
4052,NORTH PACIFIC OCEAN,not found,[]
4053,NORTH PACIFIC OCEAN,not found,[]
4062,NORTH ATLANTIC OCEAN,not found,[]
4088,COLUMBIA,not found,"[Canada, United States]"
4108,THE BALKANS,not found,[]
4147,PACIFIC OCEAN,not found,[]
4158,INDIAN OCEAN,not found,[British Indian Ocean Territory]
4189,NETHERLANDS ANTILLES,not found,[]
4205,NORTH ATLANTIC OCEAN,not found,[]
4212,COLUMBIA,not found,"[Canada, United States]"
4214,PACIFIC OCEAN,not found,[]
4271,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
4307,NORTH PACIFIC OCEAN,not found,[]
4313,MID ATLANTIC OCEAN,not found,[]
4354,PACIFIC OCEAN,not found,[]
4389,OKINAWA,not found,[Japan]
4395,JAVA,not found,[Georgia]
4412,NaN,not found,"[Thailand, China, Tuvalu, Taiwan, Province of ..."
4415,CARIBBEAN SEA,not found,[]
4418,NORTH PACIFIC OCEAN,not found,[]

# Nos quedamos con los campos que necesitamos para la tabla final

In [48]:
df.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number_1', 'case_number_2', 'original_order', 'unnamed_22',
       'unnamed_23', 'case_number_c', 'case_number_1_c', 'case_number_2_c',
       'match_all_date', 'match_1', 'match_2', 'match_3', 'date_c', 'sex_c',
       'age_is_valid_value', 'age_c', 'type_c', 'activity_c', 'country_c_2',
       'country_c', 'country_cl'],
      dtype='object')

In [51]:
df_Out=df[['original_order','date_c','case_number_c', 'case_number_1_c', 'case_number_2_c','date_c', 
           'sex_c', 'age_c', 'type_c', 'activity', 'activity_c', 'country_c', 'area', 'location',
           'name', 'injury', 'fatal', 'time', 'species', 'investigator_or_source', 'pdf', 'href_formula', 'href']]

In [52]:
df_Out.columns

Index(['original_order', 'date_c', 'case_number_c', 'case_number_1_c',
       'case_number_2_c', 'date_c', 'sex_c', 'age_c', 'type_c', 'activity',
       'activity_c', 'country_c', 'area', 'location', 'name', 'injury',
       'fatal', 'time', 'species', 'investigator_or_source', 'pdf',
       'href_formula', 'href'],
      dtype='object')

In [53]:
df_Out.columns = ['original_order', 'date', 'case_number', 'case_number_1',
       'case_number_2', 'date', 'sex', 'age', 'type', 'activity',
       'activity_categ', 'country_c', 'area', 'location', 'name', 'injury',
       'fatal', 'time', 'species', 'investigator_or_source', 'pdf',
       'href_formula', 'href']

In [54]:
df_Out.head()

,original_order,date,case_number,case_number_1,case_number_2,date,sex,age,type,activity,...,location,name,injury,fatal,time,species,investigator_or_source,pdf,href_formula,href
0,5993,2016-09-18,2016-09-18,2016-09-18,2016-09-18,2016-09-18,M,16.0,Unprovoked,Surfing,...,"New Smyrna Beach, Volusia County",male,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1,5992,2016-09-18,2016-09-18,2016-09-18,2016-09-18,2016-09-18,M,36.0,Unprovoked,Surfing,...,"New Smyrna Beach, Volusia County",Chucky Luciano,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2,5991,2016-09-18,2016-09-18,2016-09-18,2016-09-18,2016-09-18,M,43.0,Unprovoked,Surfing,...,"New Smyrna Beach, Volusia County",male,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3,5990,2016-09-17,2016-09-17,2016-09-17,2016-09-17,2016-09-17,M,NaN,Unprovoked,Surfing,...,Thirteenth Beach,Rory Angiolella,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4,5989,NaN,2016-09-15,2016-09-16,2016-09-15,NaN,M,NaN,Unprovoked,Surfing,...,Bells Beach,male,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [56]:
df_Out.to_csv('./shark_export.txt', index=False)